name: Emmanuel Vivier Photography
favicon: null
layout_spectrum: 0.17168
typography_spectrum: 0.6902219415642321
title: Emmanuel Vivier Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f5f7'
    - '#bdbdbf'
    - '#070508'
    - '#47444b'
    - '#84878f'
  brandStrength: 0.5443741565104574
  lightness: 0.512216956820339
  saturation: 0.7108724166173488
  rhythmicContrast: 0.7096301643177867
purpose: []
